"""crea tablas modulos y temas con relaciones

Revision ID: 8427e245788a
Revises: 1578bdf1547d
Create Date: 2026-06-15 23:06:17.834782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8427e245788a'
down_revision: Union[str, Sequence[str], None] = '1578bdf1547d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_curso_id'), 'modulos', ['curso_id'], unique=False)
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_table('temas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temas_id'), 'temas', ['id'], unique=False)
    op.create_index(op.f('ix_temas_modulo_id'), 'temas', ['modulo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temas_modulo_id'), table_name='temas')
    op.drop_index(op.f('ix_temas_id'), table_name='temas')
    op.drop_table('temas')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_curso_id'), table_name='modulos')
    op.drop_table('modulos')
    # ### end Alembic commands ###
